### ISSUE TITLE
please cut a release

### ISSUE THREAD

**Issue by rmoriz** [burtlo/ark#122]
Last release 0.9.0 is from June 2014. Still missing chefspec matchers https://github.com/burtlo/ark/pull/61

**Comment by wfindley** [comment]
+1

**Comment by bhouse** [comment]
+1

**Comment by dwmarshall** [comment]
I worked on this over the weekend based on the excellent contributions by @samdunne in #119 and by @brodock in #125 

Up to the moment status:

* I finally understand enough about travis/docker/kitchen to have merged what @samdunne and @brodock provided in their pull requests to get a docker-based build to do the right things.
* the ubuntu build fails on one test, so i have that test disabled at the moment
* the centos build is failing on a different test

Look at this! This is the farthest I have gotten!

https://travis-ci.org/dwmarshall/ark/builds/107867664

albeit with a commented-out test, the build passes on 3 of 4 platforms

Hopefully tonight i'll be able to shake out what's going on with centos (it has something to do with `/bin/tar`) and find out why the commented-out test was failing. Then I'll squash all of my ridiculous commits into a coherent pull request to this repo.

Once we have a predictably passing build, we can talk about cutting a release.

**Comment by rmoriz** [comment]
tar is probably just missing on that Centos 6? Do you know if the maintainers will merge your PR?

**Comment by dwmarshall** [comment]
I've been a collaborator for a few months, but I haven't had anything mergeable until today. See #126 for the final pull request. I'm sending email to burtlo right now asking about what the next step is to actually get 0.9.1 on supermarket.

**Comment by tas50** [comment]
0.10 is in the works.  Expect it in the next few days
