### ISSUE TITLE
Chef 12 deprecation in LWRP

### ISSUE THREAD

**Issue by hulu1522** [burtlo/ark#131]
I don't know if this has been reported yet but my Chef run gave me this warning that I wanted to pass on.

```
Deprecated features used!
         Using an LWRP provider by its name (Ark) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
           - /tmp/kitchen/cache/cookbooks/ark/resources/default.rb:26:in `initialize'
```

Let me know if it's something on my side.  Thanks.

**Comment by dwmarshall** [comment]
It's not something on your side. This has been fixed! ark 1.0 is on https://supermarket.chef.io/cookbooks/ark
