### ISSUE TITLE
ark resource/provider warning: strip_leading_dir attribute is deprecated

### ISSUE THREAD

**Issue by haidangwa** [burtlo/ark#132]
I am using the terraform cookbook, which has a dependency on the ark cookbook. Use of the ark resource displays this warning message on a chef run:

ark 1.0.0 was used.

`ark[terraform] action install[2016-02-10T17:08:27-08:00] WARN: DEPRECATED: strip_leading_dir attribute was deprecated. Use strip_components instead.`

**Comment by tas50** [comment]
@haidangwa This is actually a bug in the terraform cookbook.  You should submit a bug against that cookbook so they can update their use of ark.
