### ISSUE TITLE
Loads of 0-length archives in the files directory

### ISSUE THREAD

**Issue by elyscape** [burtlo/ark#133]
Commit daf4b1a3876f939ab790fca791be78a6fd409aa5 added a whole bunch of 0-length archives [in the `files/default` directory](https://github.com/burtlo/ark/tree/master/files/default) of the form `.!#####!foo.ext` and `.!#####!foo_sub.ext`. As far as I can tell, these aren't used by any of the tests and should probably be removed.

**Comment by tas50** [comment]
I meant to remove these previously. I've nuked them and released 1.0.1

**Comment by elyscape** [comment]
Thanks!
