### ISSUE TITLE
Ark seven_zip dependency...

### ISSUE THREAD

**Issue by billclark91** [burtlo/ark#141]
Ark depends on cookbook 'windows' which has it's own dependency on cookbook '7-zip'.  Why does Ark depend on yet another 'seven_zip' cookbook?  

It would be nice to leverage existing dependencies.

**Comment by tas50** [comment]
7-zip and seven_zip are from the same author, but 7-zip was deprecated.  I'll take a look at windows and get that dependency updated to the seven_zip cookbook.  Thanks for the report.

**Comment by billclark91** [comment]
Thanks for the update.  Perhaps it's just a documentation issue as the 'Contingent' cookbooks list '7-zip'.
