### ISSUE TITLE
Bump release (latest release) on Github

### ISSUE THREAD

**Issue by sandstrom** [burtlo/ark#146]
This page still shows a green badge/icon for 0.9. Great if it could be changed to `1.0.1`.
https://github.com/burtlo/ark/releases

![image](https://cloud.githubusercontent.com/assets/122287/14745748/051a3bb2-08ad-11e6-8923-7183451faa1b.png)

**Comment by tas50** [comment]
In all honesty the releases aren't used at all.  If I could disable them I would. We push artifacts to Supermarket and that's where users should consume them from as the source of truth.

**Comment by sandstrom** [comment]
@tas50 I mostly use vanilla Chef + 1-2 downloaded cookbooks (this is one of them), but what you say makes sense.

Thanks for a great cookbook! ⛵
