### ISSUE TITLE
Requiring OtherCookbooks

### ISSUE THREAD

**Issue by vigi009** [burtlo/ark#68]
I am trying to run this cookbook but when i try to upload it says that I require 3 other cookbooks called "build-essential", "7-zip", and "windows". The platform for those are windows, but the virtual machine I am using is running ubuntu, Windows keeps failing when I try to run that. How do I solve this?

**Comment by tas50** [comment]
These dependencies will be pulled in, but not used on your platform.  This is the nature of multi-platform cookbooks and shouldn't be considered a bug.
