### ISSUE TITLE
Release v0.9.1 to remove minitests

### ISSUE THREAD

**Issue by docwhat** [burtlo/ark#86]
The commit 6a382987c2f8d41c0138b2ef7d648c0a9eb479f0 removes old minitest files in files/default

Can you do a release with v0.9.1 so that it doesn't cause windows boxes (via test kitchen at least) to puke?

You should probably add all of `files/default` to `chefignore` since they all seem to be tests, anyway.

Thanks!

**Comment by thomasdziedzic** [comment]
+1 would really like a new release since there have been additional fixes like adding missing matchers that previously had to be defined manually in our specs

**Comment by samdunne** [comment]
Can we release this? The chefspec matchers would be useful

**Comment by tas50** [comment]
0.10 is on its way with the minitests removed
