### ISSUE TITLE
Ark can't find 'tar' on Mac OSX

### ISSUE THREAD

**Issue by Sauraus** [burtlo/ark#88]

**Comment by burtlo** [comment]
What version of Mac OSX?

I'm booting up a VM of a fresh installation of Yosemite (10.10.2) to see if the tar command is installed. My assumption is that it isn't until Xcode has had a chance to install the Developer Tools but I wanted to make sure there isn't another version that you are working or additional details about the scenario.

**Comment by Sauraus** [comment]
That is my scenario exactly.

**Comment by burtlo** [comment]
I seem to have `tar` on 10.10.2 without having Xcode installed. Are there other details that I am missing?

![screen shot 2015-03-18 at 11 11 08 am](https://cloud.githubusercontent.com/assets/244426/6715992/96057c98-cd5f-11e4-8ce9-73aecdf60fc8.png)

**Comment by Sauraus** [comment]
What does 'which tar' return for you?

**Comment by harmon** [comment]
Mac 10.10.3:

```
$ which tar
/usr/bin/tar
```

**Comment by tas50** [comment]
This has been fixed on master
