### ISSUE TITLE
Getting error "NoMethodError: undefined method `new' for Ark:Module" with Chef 12

### ISSUE THREAD

**Issue by superflav** [burtlo/ark#92]
Chef 12.0.0 was officially released on Dec 5 (https://www.chef.io/blog/2014/12/05/release-chef-client-12-0-0/), and soon after this announcement our Test Kitchen code that didn't specify a version with the require_chef_omnibus attribute began blowing up on Ark with ERRORs that stated

    ...had an error: NoMethodError: undefined method `new' for Ark:Module

Digging further we were able to find that the problem was in the _provider_for_action_ method in Chef's lib/chef/resource.rb.

Prior to Chef 12.0.0 release candidate, this method was declared more or less like this (taken from https://www.omniref.com/ruby/gems/chef/11.12.4/symbols/Chef::Resource/provider_for_action#line=673)

    def provider_for_action(action)
      # leverage new platform => short_name => resource
      # which requires explicitly setting provider in
      # resource class
      if self.provider
        provider = self.provider.new(self, self.run_context)
        provider.action = action
        provider
      else # fall back to old provider resolution
        Chef::Platform.provider_for_resource(self, action)
      end
    end

But as of 12.0.0.rc0, this method is now declared like this (taken from https://www.omniref.com/ruby/gems/chef/12.0.0.rc.0/symbols/Chef::Resource/provider_for_action#line=685)

    def provider_for_action(action)
      provider = run_context.provider_resolver.resolve(self, action).new(self, run_context)
      provider.action = action
      provider
    end

The code is obviously failing on _.new(selv, run_context)_ from the line that includes _run_context.provider_resolver.resolve(self, action).new(self, run_context)_, and there's no _new_ method in the Ark module, so that would seem to be it. 

### Create a new cookbook using berkshelf

    $ berks cookbook ark_with_chef_12

### In the new cookbook, make recipes/default.rb as

    ark 'tomcat_7' do
      url 'http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.32/bin/apache-tomcat-7.0.32.tar.gz'
      checksum 'c26ae0bc424e2639f5c77eb4d274a026c5a584a404dbdbb247ab6d2c3ebe8258'
      version '7'
      path  '/usr/local/tomcat'
      home_dir '/usr/local/tomcat/default'
      owner 'root'
    end

### In the new cookbook, make .kitchen.yml as

    ---
    driver:
      name: vagrant

    provisioner:
      name: chef_solo

    platforms:
      - name: ubuntu-12.04

    suites:
      - name: default
        run_list:
          - recipe[ark_with_chef_12::default]
        attributes:

### Run a kitchen setup

    $ kitchen setup

### Watch it blow up with

    [2014-12-08T22:09:09+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
    Chef Client failed. 0 resources updated in 1.091858713 seconds
    [2014-12-08T22:09:09+00:00] ERROR: ark[tomcat_7] (ark_with_chef_12::default line 20) had an error: NoMethodError: undefined method `new' for Ark:Module
    [2014-12-08T22:09:09+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    >>>>>> Converge failed on instance <default-ubuntu-1204>.
    >>>>>> Please see .kitchen/logs/default-ubuntu-1204.log for more details
    >>>>>> ------Exception-------
    >>>>>> Class: Kitchen::ActionFailed
    >>>>>> Message: SSH exited (1) for command: [sudo -E chef-solo --config /tmp/kitchen/solo.rb --json-attributes /tmp/kitchen/dna.json  --log_level info]
    >>>>>> ----------------------

**Comment by DennyZhang** [comment]
Guys, I ran into the same issue, while trying zabbix cookbook in Ubuntu 12.04.
https://supermarket.chef.io/cookbooks/zabbix

Do we have any workaround or fix on this? Thanks.

**Comment by bcg62** [comment]
I'm also seeing this happen

**Comment by martinb3** [comment]
Workaround PR at https://github.com/burtlo/ark/pull/98 seems to work.

**Comment by Sauraus** [comment]
Same here, all 'ark' installs of Ant/Groovy etc. are failing on Chef 12 because of this.

**Comment by lamont-granquist** [comment]
fixed when 12.1.0 releases in a couple weeks.

**Comment by martinb3** [comment]
12.1.0 was [released today](https://www.chef.io/blog/2015/03/03/chef-12-1-0-released/).

**Comment by burtlo** [comment]
Does this resolve the issue for everyone?

It seems like even if it does I want to remove the unnecessary name collision between the module `Ark` and the class `Chef::Resource::Ark`. So I may go ahead with something similar to issue #92.

**Comment by burtlo** [comment]
I am going to rename the module from `Ark` to `ArkLibrary` so that this issue will not bite someone with an in-between version.
