### ISSUE TITLE
minimum centos doesn't have 'tar' command

### ISSUE THREAD

**Issue by bigwheel** [burtlo/ark#95]
Then it is needed to install 'tar' package.

I guess I can do simply insert following line to [here](https://github.com/burtlo/ark/blob/master/attributes/default.rb#L16).

```ruby
pkgs += %w(tar) if platform?('centos')
```

**Comment by burtlo** [comment]
When you say minimum CentOS what version do you mean?

**Comment by sgerrand** [comment]
@burtlo: I've had this occur today on a minimal version of CentOS 6.7.

**Comment by sgerrand** [comment]
I saw this during a Test Kitchen run, using a Docker image of CentOS 6.7. The relevant part of the stack trace is here: https://gist.github.com/sgerrand/b0fa15c432d1c9f1944c

**Comment by dwmarshall** [comment]
This is what #61 was trying to fix - I'm going to have a working fix for this later today I think.

**Comment by dwmarshall** [comment]
This is fixed in #126 - I'll close the issue when 0.9.1 is released

**Comment by dwmarshall** [comment]
This has been fixed in v1.0.0
