### ISSUE TITLE
doesn't work on redhat 7

### ISSUE THREAD

**Issue by medyagh** [burtlo/ark#97]
it says unzip: command not found, isn't it supposed to install unzip if it is not installed?

**Comment by burtlo** [comment]
This is an issue.

**Comment by burtlo** [comment]
Is there a Fedora equivalent that I can consistently verify this against?

**Comment by joerocklin** [comment]
@burtlo centos 7 is going to be a better analog for RHEL than fedora will be

**Comment by sworisbreathing** [comment]
@burtlo I have the same issue on centos 6

```yaml
platforms:
  - name: centos-6.6
  - name: centos-7
```

Looking at https://github.com/phlipper/chef-zip, it appears `unzip` is installed as a separate package on rhel-based systems.

**Comment by tas50** [comment]
We're including unzip on RHEL hosts so this shouldn't be an issue on master.  My test kitchen runs on RHEL 7 execute just fine.
